### ISSUE TITLE
1.5.0 release stuck in restart loop

### ISSUE THREAD

**Issue by fredvollmer** [RoryQ/spanner-emulator#6]
The 1.5.0 release gets stuck in a restart loop on container initialization. The only log it outputs is "Attempting to create instance <instance name>".

Downgrading to 1.4.8 resolved the issue.

By the way, thanks for this wonderfully useful Docker image!

**Comment by ysakurai21** [comment]
When [I tried to run panic](https://github.com/ysakurai21/spanner-emulator/blob/4101e0997ba100dc6ffe7cf039244564dfcb2a2a/main.go#L29-L32), it seemed that gateway_main could not be found and failed at startup.
It may be that gateway_main is not included in the [latest image](gcr.io/cloud-spanner-emulator/emulator:1.5.0 ).

```
spanner-emulator-spanner-1  | panic: fork/exec ./gateway_main: no such file or directory
spanner-emulator-spanner-1  |
spanner-emulator-spanner-1  | goroutine 1 [running]:
spanner-emulator-spanner-1  | main.main()
```

**Comment by ysakurai21** [comment]
We downloaded the binaries and compared them, and found the following differences.
https://github.com/GoogleCloudPlatform/cloud-spanner-emulator#via-pre-built-linux-binaries

#### cloud-spanner-emulator_linux_amd64-1.4.9
```
% tree cloud-spanner-emulator_linux_amd64-1.4.9
cloud-spanner-emulator_linux_amd64-1.4.9
├── emulator_main
└── gateway_main

0 directories, 2 files
```

#### cloud-spanner-emulator_linux_amd64-1.5.0
```
% tree cloud-spanner-emulator_linux_amd64-1.5.0
cloud-spanner-emulator_linux_amd64-1.5.0
├── backend
│   └── query
│       ├── info_schema_columns_metadata.csv
│       └── info_schema_columns_metadata_for_index.csv
└── binaries
 ├── emulator_main
└── gateway_main_
 └── gateway_main

4 directories, 4 files
```

I don't know if this change is temporary or not, but I have created a [Pull Request](https://github.com/RoryQ/spanner-emulator/pull/7), so please check back if necessary.

**Comment by RoryQ** [comment]
Apologies I didn't see this before. I've updated 1.5.0 with a similar fix. Please let me know if it works for you.

**Comment by ysakurai21** [comment]
@RoryQ 
Thank you for your response.
I have confirmed that it works with the latest image.

```
% docker run --rm --env SPANNER_DATABASE_ID=db \
  --env SPANNER_INSTANCE_ID=inst \
  --env SPANNER_PROJECT_ID=proj \
  -p 9010:9010 -p 9020:9020 \
  roryq/spanner-emulator:latest
Unable to find image 'roryq/spanner-emulator:latest' locally
latest: Pulling from roryq/spanner-emulator
fc251a6e7981: Already exists
fda4ba87f6fb: Already exists
a1f1879bb7de: Already exists
53f6d76038a5: Already exists
f541620c7fa7: Already exists
4f4fb700ef54: Already exists
7114b9c2c661: Pull complete
Digest: sha256:56f764727c958284df2f5fa75305ae5a29dd1442142eaeb264f2c37a6ec4bbbc
Status: Downloaded newer image for roryq/spanner-emulator:latest
2023/02/09 09:13:34 attempting to create instance inst
WARNING: proto: file "google/rpc/status.proto" is already registered
        previously from: "google.golang.org/genproto/googleapis/rpc/status"
        currently from:  "unknown"
See https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

WARNING: proto: file "google/rpc/status.proto" has a name conflict over google.rpc.Status
        previously from: "google.golang.org/genproto/googleapis/rpc/status"
        currently from:  "unknown"
See https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

WARNING: proto: message google.rpc.Status is already registered
        previously from: "google.golang.org/genproto/googleapis/rpc/status"
        currently from:  "unknown"
See https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

2023/02/09 09:13:35 instance created
2023/02/09 09:13:35 attempting to create database db
2023/02/09 09:13:35 gateway.go:140: Cloud Spanner emulator running.
2023/02/09 09:13:35 gateway.go:141: REST server listening at 0.0.0.0:9020
2023/02/09 09:13:35 gateway.go:142: gRPC server listening at 0.0.0.0:9010
2023/02/09 09:13:35 database created
```

```
% spanner-cli -p proj -i inst -d db
Connected.
spanner> SHOW DATABASES;
+----------+
| Database |
+----------+
| db       |
+----------+
1 rows in set (0.00 sec)
```

#7 is no longer needed, so I closed it.
